name: Quotes Gen
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 6 * * *'
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - name: Install Bark
        run: |
          pip install git+https://github.com/suno-ai/bark.git
     - name: Download  Models 
        run: |
            python main.py
           
           
